# Generated by Django 6.0 on 2025-12-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('numero_factura', models.CharField(blank=True, default='', max_length=80)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='CONFIRMADA', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('nit', models.CharField(blank=True, default='', max_length=40)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('canal', models.CharField(choices=[('TIENDA', 'Tienda'), ('DOMICILIO', 'Domicilio'), ('WHATSAPP', 'WhatsApp'), ('ONLINE', 'Online')], default='TIENDA', max_length=20)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('QR', 'QR'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='CONFIRMADA', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('categoria_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='core.categoriagasto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=180)),
                ('unidad', models.CharField(default='unidad', max_length=20)),
                ('iva', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_alt', models.CharField(blank=True, default='', max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('DEVOLUCION', 'Devolución')], max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=40)),
                ('referencia_id', models.BigIntegerField(blank=True, null=True)),
                ('entrada', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('salida', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('saldo_cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('iva', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=18)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_detalle', to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.proveedor'),
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('descuento_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('costo_unitario_en_venta', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ganancia_linea', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.venta')),
            ],
        ),
    ]
