# Generated by Django 6.0 on 2025-12-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeudaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=12)),
                ('total_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('documento', models.CharField(blank=True, default='', max_length=40)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=60, unique=True, verbose_name='SKU'),
        ),
        migrations.CreateModel(
            name='AbonoDeudaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=60)),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='core.deudacliente')),
            ],
        ),
        migrations.CreateModel(
            name='DeudaClienteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=18)),
                ('precio_unitario_inicial', models.DecimalField(decimal_places=2, max_digits=18)),
                ('iva', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=18)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.deudacliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas_clientes_detalle', to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DeudaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('numero_factura', models.CharField(blank=True, default='', max_length=80)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=12)),
                ('total_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas', to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='AbonoDeudaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=60)),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='core.deudaproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DeudaProveedorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=18)),
                ('costo_unitario_inicial', models.DecimalField(decimal_places=6, max_digits=18)),
                ('iva', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=18)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.deudaproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas_proveedor_detalle', to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='deudacliente',
            name='deudor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas', to='core.deudor'),
        ),
    ]
