# Generated by Django 6.0 on 2025-12-22 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='deudor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.deudor'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('QR', 'QR'), ('DEUDA', 'Deuda'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
    ]
