# Generated by Django 6.0 on 2025-12-22 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venta_deudor_alter_venta_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudacliente',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deuda', to='core.venta'),
        ),
    ]
