# Generated by Django 6.0 on 2025-12-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_deudacliente_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="ProductoResena",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(blank=True, default="", max_length=120)),
                ("rating", models.PositiveSmallIntegerField()),
                ("comentario", models.TextField(blank=True, default="")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("producto", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resenas", to="core.producto")),
            ],
            options={
                "ordering": ("-creado_en",),
            },
        ),
    ]

