# Generated by Django 6.0 on 2025-12-23 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_descripcion_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=160)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('ENVIADA', 'Enviada'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='EN_PROCESO', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VentaWebItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_web', to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ventaweb')),
            ],
        ),
    ]
