# Generated by Django 6.0 on 2025-12-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_productoresena_usuario"),
        ("core", "0007_ventaweb_ventawebitem"),
    ]

    operations = []

