# Generated by Django 6.0 on 2025-12-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_merge_0007_productoresena_usuario_0007_ventaweb_ventawebitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productos/galeria/",
                    ),
                ),
                ("imagen_alt", models.CharField(blank=True, default="", max_length=180)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="core.producto",
                    ),
                ),
            ],
            options={
                "ordering": ("orden", "id"),
            },
        ),
    ]
